#!/usr/bin/env node
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { cac } from 'cac';

const fnRegex = /pub\s+export\s+fn\s+([a-zA-Z0-9_]+)\s*\(([^)]*)\)\s*([^{\s]+)/g;

const getRecursiveFiles = (dir: string, extension: string): string[] => {
    let files: string[] = [];
    if (!fs.existsSync(dir)) return files;
    
    const items = fs.readdirSync(dir, { withFileTypes: true });
    for (const item of items) {
        const fullPath = path.join(dir, item.name);
        if (item.isDirectory()) {
            if (item.name.startsWith('.')) continue;
            files = files.concat(getRecursiveFiles(fullPath, extension));
        } else if (item.name.endsWith(extension)) {
            files.push(fullPath);
        }
    }
    return files;
};

const mapZigTypeToTS = (zigType: string): string => {
    zigType = zigType.trim();
    if (zigType === 'void') return 'void';
    if (zigType === 'bool') return 'boolean';
    
    if (zigType.includes('Vec2Result') || zigType.includes('Vec2') || zigType === 'struct{f64,f64}') {
        return '[number, number]';
    }
    if (zigType.includes('Vec3Result') || zigType.includes('Vec3') || zigType === 'struct{f64,f64,f64}') {
        return '[number, number, number]';
    }
    if (zigType.includes('f32') || zigType.includes('f64') || 
        zigType.includes('i32') || zigType.includes('u32') || 
        zigType.includes('usize') || zigType.includes('isize') ||
        zigType.startsWith('[*]') || zigType.startsWith('*')) {
        return 'number';
    }
    return 'any';
};

const extractJsDoc = (fileContent: string, matchIndex: number): string => {
    const textBefore = fileContent.substring(0, matchIndex).trim();
    const lines = textBefore.split('\n');
    let commentLines: string[] = [];

    for (let i = lines.length - 1; i >= 0; i--) {
        const line = lines[i]!.trim();
        if (line.startsWith('///')) {
            commentLines.unshift(line.replace('///', '').trim());
        } else if (line.startsWith('//')) {
            commentLines.unshift(line.replace('//', '').trim());
        } else if (line.length === 0) {
            continue;
        } else {
            break;
        }
    }

    if (commentLines.length === 0) return '';

    return `    /**\n${commentLines.map(l => `     * ${l}`).join('\n')}\n     */\n`;
};

const generateArtifacts = (zigFiles: string[], options: { outputDir: string; tsOutputDir: string | null; outputName: string; isTypeScriptMode: boolean }) => {
    const { outputDir, outputName, isTypeScriptMode, tsOutputDir } = options;

    let dtsFunctions = '';
    let jsFunctions = '';
    
    let tsDirectVariables = '';
    let tsInitAssignments = '';
    let tsExportList = '';

    for (const file of zigFiles) {
        const fileContent = fs.readFileSync(file, 'utf-8');
        let match;
        fnRegex.lastIndex = 0;

        while ((match = fnRegex.exec(fileContent)) !== null) {
            const matchIndex = match.index;
            const fnName = match[1];
            const rawParams = match[2];
            const rawReturn = match[3];

            if (fnName === 'zig_bind_alloc' || fnName === 'zig_bind_reset') continue;

            const jsDocBlock = extractJsDoc(fileContent, matchIndex);

            const tsParamsList: string[] = [];
            const jsParamsList: string[] = [];

            if (rawParams!.trim().length > 0) {
                rawParams!.split(',').forEach(p => {
                    const parts = p.split(':');
                    if (parts.length >= 2) {
                        const pName = parts[0]!.trim();
                        const pType = mapZigTypeToTS(parts[1]!);
                        tsParamsList.push(`${pName}: ${pType}`);
                        jsParamsList.push(pName);
                    }
                });
            }

            const tsParams = tsParamsList.join(', ');
            const jsParams = jsParamsList.join(', ');
            const returnType = mapZigTypeToTS(rawReturn!);

            jsFunctions += `${jsDocBlock}        ${fnName}(${jsParams}) {\n            return e.${fnName}(${jsParams});\n        },\n`;
            dtsFunctions += `${jsDocBlock}    ${fnName}(${tsParams}): ${returnType};\n`;

            tsDirectVariables += `${jsDocBlock}export let ${fnName}: (${tsParams}) => ${returnType} = null as any;\n`;
            tsInitAssignments += `    ${fnName} = e.${fnName} as any;\n`;
        }
    }

    if (isTypeScriptMode) {
        const finalTsDir = tsOutputDir! ? tsOutputDir : outputDir;
        fs.mkdirSync(finalTsDir, { recursive: true });

        const tsPath = path.join(finalTsDir, `${outputName}.ts`);
        const tsContent = `// AUTOMATICALLY GENERATED BY ZIG-BIND CLI

export let zig_bind_alloc: (bytes: number) => number = null as any;
export let zig_bind_reset: () => void = null as any;
${tsDirectVariables}
/**
 * Connects your WebAssembly instance exports directly to top-level variables.
 * Call this exactly once upon module initialization.
 */
export function initWasmBindings(wasmInstance: WebAssembly.Instance): void {
    const e = wasmInstance.exports;
    zig_bind_alloc = e.zig_bind_alloc as any;
    zig_bind_reset = e.zig_bind_reset as any;
${tsInitAssignments}
}
`;
        fs.writeFileSync(tsPath, tsContent);
    } else {
        const jsPath = path.join(outputDir, `${outputName}.js`);
        const dtsPath = path.join(outputDir, `${outputName}.d.ts`);
        const dtsContent = `// AUTOMATICALLY GENERATED BY ZIG-BIND CLI\nexport interface WasmModuleWrapper {\n    zig_bind_alloc(bytes: number): number;\n    zig_bind_reset(): void;\n${dtsFunctions}}\nexport function createWasmWrapper(wasmInstance: WebAssembly.Instance): WasmModuleWrapper;\n`;
        const jsContent = `// AUTOMATICALLY GENERATED BY ZIG-BIND CLI\nexport function createWasmWrapper(wasmInstance) {\n    const e = wasmInstance.exports;\n    return {\n        zig_bind_alloc: e.zig_bind_alloc,\n        zig_bind_reset: e.zig_bind_reset,\n${jsFunctions}    };\n}\n`;
        fs.writeFileSync(dtsPath, dtsContent);
        fs.writeFileSync(jsPath, jsContent);
    }
};

const cli = cac('zig-bind');

cli.command('build <inputPaths...>', 'Compiles a Zig file, files, or a directory of Zig files')
   .option('--out <dir>', 'Output directory', { default: './dist' })
   .option('--ts [dir]', 'Output a single unified .ts file instead of separate js/d.ts pairs. Optional destination folder path can be passed.')
   .option('--shared', 'Enable shared memory and atomics for multi-threaded worker pools')
   .option('--mode <mode>', 'Build mode: debug, fast, small', { default: 'fast' })
   .option('--clean', 'Force a clean build by clearing caches')
   .option('--standalone', 'Uses standalone (No WASI)')
   .option('--nosimd', 'Removes simd in compilation')
   .action((inputPaths: string | string[], options) => {
       const outputDir = path.resolve(options.out || './dist');
       const isShared = !!options.shared;
       const mode: string = options.mode;
       const standalone = options.standalone;
       const isTypeScriptMode = options.ts !== undefined && options.ts !== false;
       const tsOutputDir = (typeof options.ts === 'string') ? path.resolve(options.ts) : null;
       const simd = options.nosimd == undefined;

       const rawPaths = Array.isArray(inputPaths) 
           ? inputPaths 
           : (inputPaths ? [inputPaths] : []);

       const normalizedInputPaths = rawPaths.map(p => path.resolve(p).replace(/\\/g, '/'));

       let zigFiles: string[] = [];

       for (const inputPath of normalizedInputPaths) {
           const absolutePath = path.resolve(inputPath);
           if (!fs.existsSync(absolutePath)) {
               console.error(`Error: Input path not found at ${absolutePath}`);
               process.exit(1);
           }

           const stat = fs.statSync(absolutePath);
           if (stat.isDirectory()) {
               zigFiles = zigFiles.concat(getRecursiveFiles(absolutePath, '.zig'));
           } else if (absolutePath.endsWith('.zig')) {
               zigFiles.push(absolutePath);
           }
       }

       if (zigFiles.length === 0) {
           console.error(`Error: No .zig files found to compile.`);
           process.exit(1);
       }

       fs.mkdirSync(outputDir, { recursive: true });

       const firstFileAbsolute = zigFiles[0];
       const inputDir = path.dirname(firstFileAbsolute!);
       const buildZigPath = path.join(inputDir, 'build.zig');
       const coreEnginePath = path.resolve(import.meta.dirname, '../zig/zig_bind.zig').replace(/\\/g, '/');
       
       const outputName = zigFiles.length === 1 ? path.basename(firstFileAbsolute!, '.zig') : 'math_bundle';
       const finalWasmOutput = path.join(outputDir, `${outputName}.wasm`);

       const libDir = path.join(inputDir, '../lib');
       let cFiles: string[] = [];
       if (fs.existsSync(libDir)) {
           cFiles = getRecursiveFiles(libDir, '.c');
       }

       const baseCFlags = ["-O3", "-mbulk-memory", "-Ilib"];
       if (simd) baseCFlags.push("-msimd128")
       if (isShared) baseCFlags.push("-matomics");
       const formattedCFlags = baseCFlags.map(f => `"${f}"`).join(', ');

       const cSourceInclusion = cFiles.map(file => {
           const relativePath = path.relative(inputDir, file).replace(/\\/g, '/');
           return `
    exe.root_module.addCSourceFile(.{
        .file = b.path("${relativePath}"),
        .flags = &.{${formattedCFlags}},
    });`;
       }).join('');

       const includePath = fs.existsSync(libDir) ? `exe.root_module.addIncludePath(b.path("lib"));` : '';

       const injectPath = path.join(inputDir, 'build_inject.zig');
       let injectedCode = '';
       if (fs.existsSync(injectPath)) injectedCode = fs.readFileSync(injectPath, 'utf-8');

       const optimizeMap: Record<string, string> = {
           'debug': '.Debug',
           'fast': '.ReleaseFast',
           'small': '.ReleaseSmall'
       };
       const optimize: string = optimizeMap[mode] || '.ReleaseFast';

       const mainEntryFilename = `_bundle_entry.zig`;
       const bundleEntryPath = path.join(inputDir, mainEntryFilename);
       
       const explicitImports = zigFiles.map((file) => {
           const relativePath = path.relative(inputDir, file).replace(/\\/g, '/');
           return `    _ = @import("${relativePath}");`;
       }).join('\n');

       const allocatorCode = `
comptime {
${explicitImports}
}

// INJECTED MEMORY
const zb = @import("zig_bind");

pub export fn zig_bind_alloc(bytes: usize) ?[*]u8 { 
    return zb.alloc(bytes); 
}

pub export fn zig_bind_reset() void { 
    zb.reset(); 
}
`;
       
       fs.writeFileSync(bundleEntryPath, allocatorCode);
       const generatedMainCleanup = () => {
           if (fs.existsSync(bundleEntryPath)) fs.unlinkSync(bundleEntryPath);
       };

       const buildZigContent = `
// THIS FILE IS AUTO GENERATED, TO INJECT LINES MAKE A 'build_inject.zig' FILE IN THE INPUT DIRECTORY       
const std = @import("std");
pub fn build(b: *std.Build) void {
    ${(!simd && !isShared) ? 'const' : 'var'} features = std.Target.Cpu.Feature.Set.empty;
    ${isShared ? `
    features.addFeature(@intFromEnum(std.Target.wasm.Feature.atomics));
    features.addFeature(@intFromEnum(std.Target.wasm.Feature.bulk_memory));
    ` : ''}
    ${simd ? `features.addFeature(@intFromEnum(std.Target.wasm.Feature.simd128));` : ``}

    const target = b.resolveTargetQuery(.{
        .cpu_arch = .wasm32,
        .os_tag = ${standalone ? '.freestanding' : '.wasi'},
        .cpu_features_add = features,
    });

    const root_mod = b.createModule(.{
        .root_source_file = b.path("${mainEntryFilename}"),
        .target = target,
        .optimize = ${optimize},
    });

    const exe = b.addExecutable(.{
        .name = "${outputName}",
        .root_module = root_mod,
    });

    ${standalone ? '' : 'exe.root_module.link_libc = true;'}
    exe.entry = .disabled;
    exe.rdynamic = true;
    ${isShared ? `
    exe.import_memory = true;
    exe.shared_memory = true;
    exe.max_memory = 8192 * 65536;
    ` : ''}
    
    ${includePath}
    ${cSourceInclusion}
    ${injectedCode}

    const zb_mod = b.addModule("zig_bind", .{
        .root_source_file = .{ .cwd_relative = "${coreEnginePath}" },
    });
    exe.root_module.addImport("zig_bind", zb_mod);

    const install = b.addInstallArtifact(exe, .{});
    b.getInstallStep().dependOn(&install.step);
}
`;

       fs.writeFileSync(buildZigPath, buildZigContent);

       console.log(`Compiling target files (${zigFiles.length} files total)...`);

       try {
           const localCacheDir = path.join(inputDir, '.zig-global-cache');
           const cleanArg = options.clean ? "--cache-clean" : "";

           execSync(`zig build --global-cache-dir "${localCacheDir}" ${cleanArg}`, { 
               cwd: inputDir,
               stdio: 'inherit',
               env: { ...process.env }
           });

           const buildOutputPath = path.join(inputDir, 'zig-out', 'bin', `${outputName}.wasm`);
           if (fs.existsSync(buildOutputPath)) {
               fs.copyFileSync(buildOutputPath, finalWasmOutput);
               console.log(`Done! Generated Wasm at: ${finalWasmOutput}`);

               console.log(`Generating wrapper bindings and parsing docs...`);
               generateArtifacts(zigFiles, { outputDir, outputName, isTypeScriptMode, tsOutputDir });
               console.log(`Bindings and docs generated successfully!`);
           }
       } catch (err) {
           console.error('Zig Compilation Failed.');
       } finally {
           generatedMainCleanup();
           const dirs = ['zig-out', '.zig-cache', '.zig-global-cache', '.zig-appdata'];
           for (const dir of dirs) {
               const p = path.join(inputDir, dir);
               if (fs.existsSync(p)) fs.rmSync(p, { recursive: true, force: true });
           }
       }
   });

cli.help();
cli.parse();